<?php
session_start();
require_once '../PROCESS/db_config.php';

// Check if user is logged in and is staff
if (!isset($_SESSION['user_id']) || $_SESSION['user_role'] !== 'staff') {
    exit('Unauthorized');
}

// Get filter parameters
$dateFrom = $_GET['date_from'] ?? date('Y-m-01');
$dateTo = $_GET['date_to'] ?? date('Y-m-d');
$statusFilter = $_GET['status'] ?? '';
$searchTerm = $_GET['search'] ?? '';

// Build query for orders
$query = "SELECT o.*, COUNT(oi.id) as item_count, SUM(oi.quantity) as total_quantity
          FROM orders o
          LEFT JOIN order_items oi ON o.id = oi.order_id
          WHERE DATE(o.created_at) BETWEEN ? AND ?";

$params = [$dateFrom, $dateTo];
$types = "ss";

if (!empty($statusFilter)) {
    $query .= " AND o.status = ?";
    $params[] = $statusFilter;
    $types .= "s";
}

if (!empty($searchTerm)) {
    $query .= " AND (o.order_number LIKE ? OR o.customer_name LIKE ? OR o.customer_email LIKE ?)";
    $searchWildcard = "%{$searchTerm}%";
    $params[] = $searchWildcard;
    $params[] = $searchWildcard;
    $params[] = $searchWildcard;
    $types .= "sss";
}

$query .= " GROUP BY o.id ORDER BY o.created_at DESC";

$stmt = $conn->prepare($query);
if (!empty($params)) {
    $stmt->bind_param($types, ...$params);
}
$stmt->execute();
$result = $stmt->get_result();
$orders = [];
$totalRevenue = 0;

while ($row = $result->fetch_assoc()) {
    $orders[] = $row;
    $totalRevenue += $row['total_amount'];
}

// Create CSV content (Excel-compatible format)
$filename = 'sales_report_' . date('Y-m-d-H-i-s') . '.csv';

// Set headers
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

// BOM for Excel UTF-8 support
echo "\xEF\xBB\xBF";

// Create file handle
$output = fopen('php://output', 'w');

// Write title row
fputcsv($output, ['CLOTHING MANAGEMENT SYSTEM - SALES REPORT']);
fputcsv($output, []);
fputcsv($output, ['Report Date Range', date('M d, Y', strtotime($dateFrom)) . ' to ' . date('M d, Y', strtotime($dateTo))]);
fputcsv($output, ['Report Generated', date('M d, Y H:i A')]);
fputcsv($output, ['Generated By', $_SESSION['user_name'] ?? 'Staff User']);
fputcsv($output, []);

// Write summary section
fputcsv($output, ['SUMMARY STATISTICS']);
fputcsv($output, ['Total Orders', count($orders)]);
fputcsv($output, ['Total Revenue', '₱' . number_format($totalRevenue, 2)]);
fputcsv($output, ['Average Order Value', '₱' . (count($orders) > 0 ? number_format($totalRevenue / count($orders), 2) : '0.00')]);
fputcsv($output, []);

// Write order header
fputcsv($output, [
    'Order Number',
    'Customer Name',
    'Email',
    'Phone',
    'Items Count',
    'Total Quantity',
    'Total Amount',
    'Order Status',
    'Payment Status',
    'Shipping Address',
    'Order Date',
    'Notes'
]);

// Write order data
foreach ($orders as $order) {
    fputcsv($output, [
        $order['order_number'],
        $order['customer_name'],
        $order['customer_email'],
        $order['customer_phone'],
        $order['item_count'],
        $order['total_quantity'] ?? 0,
        $order['total_amount'],
        strtoupper($order['status']),
        strtoupper($order['payment_status']),
        $order['shipping_address'],
        date('M d, Y H:i A', strtotime($order['created_at'])),
        $order['notes'] ?? ''
    ]);
    
    // Get order items for this order
    $itemsQuery = "SELECT oi.*, p.product_name, p.category 
                   FROM order_items oi 
                   LEFT JOIN products p ON oi.product_id = p.id 
                   WHERE oi.order_id = ?";
    $itemsStmt = $conn->prepare($itemsQuery);
    $itemsStmt->bind_param("i", $order['id']);
    $itemsStmt->execute();
    $itemsResult = $itemsStmt->get_result();
    
    if ($itemsResult->num_rows > 0) {
        fputcsv($output, ['--- Item Details ---']);
        fputcsv($output, ['  Product Name', 'Category', 'Quantity', 'Unit Price', 'Subtotal']);
        
        while ($item = $itemsResult->fetch_assoc()) {
            fputcsv($output, [
                '  ' . ($item['product_name'] ?? 'N/A'),
                $item['category'] ?? 'N/A',
                $item['quantity'],
                '₱' . number_format($item['price'], 2),
                '₱' . number_format($item['subtotal'], 2)
            ]);
        }
        fputcsv($output, []);
    }
}

// Write footer
fputcsv($output, []);
fputcsv($output, ['Report Footer']);
fputcsv($output, ['Thank you for using Clothing Management System']);
fputcsv($output, ['For more information, contact: admin@clothing.local']);

fclose($output);
?>